selection = ["apple", "brace", "cloud", "dream", "eagle", "frame", "grape", "heart", "ideal", 
    "joker", "knife", "lemon", "mango", "night", "olive", "piano", "queen", "river", 
    "stone", "table", "unity", "vapor", "world", "zebra", "yacht", "toast", "sugar", 
    "sword", "trick", "tiger", "quirk", "punch", "peach", "orbit", "nifty", "maple",
    "lucky", "llama", "jolly", "ivory", "hotel", "glitch", "frost", "fuzzy", "ghoul",
    "flint", "ember", "delta", "crown", "crisp", "camel", "bacon", "aback", "about",
    "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
    "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow",
    "alone", "along", "alter", "among", "ample", "amuse", "angel", "anger", "angle",
    "angry", "apart", "apply", "argue", "arise", "aside", "asset", "audio", "audit",
    "avoid", "awake", "aware", "awful", "beach", "beast", "begin", "birth", "blame",
    "blast", "blend", "bless", "blind", "block", "blood", "board", "boast", "boost",
    "booth", "brave", "break", "brick", "brief", "bring", "broad", "brook", "brush",
    "build", "burst", "buyer", "cable", "carry", "cause", "chain", "chair", "charm",
    "chase", "cheat", "check", "cheer", "chest", "chief", "chill", "choke", "civic",
    "civil", "claim", "clean", "clear", "clerk", "click", "climb", "clock", "close",
    "cloud", "coach", "coast", "cocoa", "color", "comic", "crowd", "crown", "cruel",
    "crust", "cycle", "dairy", "dance", "death", "delay", "dense", "depth", "devil",
    "diary", "digit", "dirty", "doubt", "dozen", "draft", "drama", "drain", "dream",
    "dress", "drill", "drink", "drive", "drown", "eagle", "early", "earth", "elbow",
    "elite", "email", "empty", "enemy", "enjoy", "equal", "error", "essay", "event",
    "every", "exact", "exist", "extra", "faint", "fairy", "faith", "false", "fancy",
    "fatal", "feast", "fence", "fiber", "field", "fight", "final", "flame", "flash",
    "float", "flour", "focus", "force", "forge", "frame", "fraud", "fresh", "front",
    "fruit", "funny", "fuzzy", "ghost", "giant", "glory", "grace", "grand", "grant",
    "grave", "great", "greet", "grill", "groan", "gross", "group", "guard", "guess"
]
